/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ClienteDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Cliente;
import model.TelaCadastroModelo;

public class TelaVisualizacao extends javax.swing.JFrame {

    // Formata a data do padrão US para o padrão BR
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form TelaCadastro
     */
    public TelaVisualizacao() {
        initComponents();
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDeslogar = new javax.swing.JButton();
        botaoNovoCliente = new javax.swing.JButton();
        jPanelBuscar = new javax.swing.JPanel();
        caixaBuscarCliente = new javax.swing.JTextField();
        jLabelBuscarCliente = new javax.swing.JLabel();
        botaoBuscar = new javax.swing.JButton();
        jPanelResumoDosClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableClientesGeral = new javax.swing.JTable();
        jButtonAtualizarDados = new javax.swing.JButton();
        jPanelImc = new javax.swing.JPanel();
        jLabelImc = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jToggleButtonCalcularImc = new javax.swing.JToggleButton();
        jLabelSelecionarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);

        cabecalho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("RESUMO DOS CLIENTES");

        jButtonDeslogar.setText("Deslogar");
        jButtonDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeslogarActionPerformed(evt);
            }
        });

        botaoNovoCliente.setText("Novo Cliente");
        botaoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoNovoCliente)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeslogar)
                .addGap(18, 18, 18))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButtonDeslogar)
                    .addComponent(botaoNovoCliente))
                .addContainerGap())
        );

        jPanelBuscar.setPreferredSize(new java.awt.Dimension(457, 42));

        jLabelBuscarCliente.setText("Buscar Cliente :");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addComponent(jLabelBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caixaBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoBuscar)
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscar)
                    .addComponent(caixaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Cadastrados"));

        jTableClientesGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CPF", "Nome", "Data Nascimento", "Altura", "Peso"
            }
        ));
        jTableClientesGeral.setRowHeight(25);
        jTableClientesGeral.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableClientesGeral.setShowGrid(true);
        jScrollPane3.setViewportView(jTableClientesGeral);
        jTableClientesGeral.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (jTableClientesGeral.getSelectedRow() > -1) {
                    jToggleButtonCalcularImc.setSelected(false);
                    jPanelImc.setVisible(false);
                }
            }
        });

        jButtonAtualizarDados.setText("Atualizar Dados");
        jButtonAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarDadosActionPerformed(evt);
            }
        });

        jPanelImc.setBorder(javax.swing.BorderFactory.createTitledBorder("IMC"));

        jButton4.setText("Baixar Informações");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelImcLayout = new javax.swing.GroupLayout(jPanelImc);
        jPanelImc.setLayout(jPanelImcLayout);
        jPanelImcLayout.setHorizontalGroup(
            jPanelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImc, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanelImcLayout.setVerticalGroup(
            jPanelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImcLayout.createSequentialGroup()
                .addGroup(jPanelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImcLayout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jLabelImc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToggleButtonCalcularImc.setText("Calcular IMC");
        jToggleButtonCalcularImc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jToggleButtonCalcularImcFocusLost(evt);
            }
        });
        jToggleButtonCalcularImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCalcularImcActionPerformed(evt);
            }
        });

        jLabelSelecionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSelecionarCliente.setText("Antes de realizar essas operações selecione um cliente!");

        javax.swing.GroupLayout jPanelResumoDosClientesLayout = new javax.swing.GroupLayout(jPanelResumoDosClientes);
        jPanelResumoDosClientes.setLayout(jPanelResumoDosClientesLayout);
        jPanelResumoDosClientesLayout.setHorizontalGroup(
            jPanelResumoDosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addGroup(jPanelResumoDosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumoDosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResumoDosClientesLayout.createSequentialGroup()
                        .addComponent(jButtonAtualizarDados)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonCalcularImc)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSelecionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelResumoDosClientesLayout.setVerticalGroup(
            jPanelResumoDosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResumoDosClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResumoDosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelecionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResumoDosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAtualizarDados)
                        .addComponent(jToggleButtonCalcularImc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelImc.setVisible(false);
        jLabelSelecionarCliente.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelResumoDosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResumoDosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(950, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeslogarActionPerformed
        new TelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDeslogarActionPerformed

    private void botaoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoClienteActionPerformed
        new TelaCadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoNovoClienteActionPerformed

    private void jButtonAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDadosActionPerformed
        TelaCadastroModelo model = new TelaCadastroModelo();
        if (jTableClientesGeral.getSelectedRow() == -1) {
            jLabelSelecionarCliente.setVisible(true);
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    jLabelSelecionarCliente.setVisible(false);
                    timer.cancel();
                }
            };
            timer.schedule(task, 3000L);
        } else {
            model.setId(Integer.parseInt(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 0).toString()));
            model.setCpf(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 1).toString());
            model.setNome(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 2).toString());
            try {
                model.setDataNascimento(sdf.parse(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 3).toString()));
            } catch (ParseException ex) {
                throw new RuntimeException(ex);
            }
            model.setAltura(Double.parseDouble(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 4).toString()));
            model.setPeso(Double.parseDouble(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 5).toString()));

            TelaCliente frm = new TelaCliente();
            frm.readTableCliente(model);
            frm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonAtualizarDadosActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        TelaCadastroModelo model = new TelaCadastroModelo();
        model.setNome(caixaBuscarCliente.getText());
        TelaCliente frm = new TelaCliente();
        try {
            frm.readTableClientePorNome(model.getNome());
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void jToggleButtonCalcularImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCalcularImcActionPerformed
        if (jTableClientesGeral.getSelectedRow() == -1) {
            jLabelSelecionarCliente.setVisible(true);
            jToggleButtonCalcularImc.setSelected(false);
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    jLabelSelecionarCliente.setVisible(false);
                    timer.cancel();
                }
            };
            timer.schedule(task, 3000L);

        } else {
            int id = (Integer.parseInt(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 0).toString()));
            Cliente cliente;
            try {
                cliente = new ClienteDAO().getClientePorId(id);
                if (jToggleButtonCalcularImc.isSelected()) {
                    jPanelImc.setVisible(true);
                    jLabelImc.setText(cliente.pesoIdealAdulto(cliente));
                } else {
                    jPanelImc.setVisible(false);
                }
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }
        }
    }//GEN-LAST:event_jToggleButtonCalcularImcActionPerformed

    private void jToggleButtonCalcularImcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jToggleButtonCalcularImcFocusLost

    }//GEN-LAST:event_jToggleButtonCalcularImcFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ClienteDAO clienteDao = new ClienteDAO();
        int id = (Integer.parseInt(jTableClientesGeral.getModel().getValueAt(jTableClientesGeral.getSelectedRow(), 0).toString()));
        try {
            clienteDao.baixarInformacoes(id);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoNovoCliente;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JTextField caixaBuscarCliente;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAtualizarDados;
    private javax.swing.JButton jButtonDeslogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelImc;
    private javax.swing.JLabel jLabelSelecionarCliente;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelImc;
    private javax.swing.JPanel jPanelResumoDosClientes;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClientesGeral;
    private javax.swing.JToggleButton jToggleButtonCalcularImc;
    // End of variables declaration//GEN-END:variables

    public void readTable() {
        // Popula a tabela na TelaCliente com todos os clientes encontrados no DB
        DefaultTableModel modelo = (DefaultTableModel) jTableClientesGeral.getModel();
        modelo.setNumRows(0);
        TableColumnModel tcm = jTableClientesGeral.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<>(modelo);
        jTableClientesGeral.setRowSorter(sorter);
        ClienteDAO clienteDao = new ClienteDAO();

        try {
            for (Cliente cliente : clienteDao.getClientes()) {
                modelo.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getCpf(),
                    cliente.getNome(),
                    sdf.format(cliente.getDataNascimento()),
                    cliente.getAltura(),
                    cliente.getPeso()
                });
            }
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

}
