/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ClienteDAO;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;
import model.Cliente;
import model.TelaCadastroModelo;

public class TelaCadastro extends javax.swing.JFrame {

    // Formata a data do padrão US para o padrão BR
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    // Máscara que determina o padrão que os dados serão inseridos
    MaskFormatter mascaraCpf;
    MaskFormatter mascaraDataNascimento;
    MaskFormatter mascaraAltura;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaCadastro() {
        initComponents();
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastrarCliente = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCadastrados = new javax.swing.JTable();
        jPanelInserirNovosDados1 = new javax.swing.JPanel();
        jLabelInsiraOsNovosDados1 = new javax.swing.JLabel();
        jButtonCancelar1 = new javax.swing.JButton();
        jButtonSalvar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelDadosCadastradosSucesso = new javax.swing.JLabel();
        jLabelPreencherDados = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jFormattedTextFieldAltura = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPeso = new javax.swing.JFormattedTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jPanelAtencao = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        cabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVisaoGeral = new javax.swing.JButton();
        jButtonDeslogar = new javax.swing.JButton();
        jPanelBuscar = new javax.swing.JPanel();
        caixaBuscarCliente = new javax.swing.JTextField();
        jLabelBuscarCliente = new javax.swing.JLabel();
        botaoBuscar = new javax.swing.JButton();
        jLabelCadastroJaExiste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setMinimumSize(null);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Cadastrados"));

        jTableCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Data Nascimento", "Altura", "Peso"
            }
        ));
        jTableCadastrados.setRowHeight(25);
        jTableCadastrados.setRowSelectionAllowed(false);
        jTableCadastrados.setShowGrid(true);
        jScrollPane4.setViewportView(jTableCadastrados);
        jTableCadastrados.getAccessibleContext().setAccessibleName("");

        jLabelInsiraOsNovosDados1.setText("Insira os dados do novo cliente:");

        jButtonCancelar1.setText("Limpar");
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });

        jLabelDadosCadastradosSucesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDadosCadastradosSucesso.setText("Dados cadastrados com sucesso!");

        jLabelPreencherDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPreencherDados.setText("Preencha todos os dados corretamente antes de salvar!");

        jLabelCpf.setText("CPF:");

        jLabelAltura.setText("Altura:");

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabelNome.setText("Nome:");

        jLabelPeso.setText("Peso:");

        try {
            jFormattedTextFieldAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldAltura.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jFormattedTextFieldPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPeso.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabelDataNascimento.setText("Data de Nascimento:");

        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        javax.swing.GroupLayout jPanelInserirNovosDados1Layout = new javax.swing.GroupLayout(jPanelInserirNovosDados1);
        jPanelInserirNovosDados1.setLayout(jPanelInserirNovosDados1Layout);
        jPanelInserirNovosDados1Layout.setHorizontalGroup(
            jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInsiraOsNovosDados1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                        .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                                .addComponent(jLabelAltura)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                                .addComponent(jLabelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelPeso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabelDataNascimento))
                            .addComponent(jFormattedTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelInserirNovosDados1Layout.createSequentialGroup()
                                .addComponent(jButtonCancelar1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar1))))
                    .addComponent(jLabelDadosCadastradosSucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreencherDados, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanelInserirNovosDados1Layout.setVerticalGroup(
            jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInserirNovosDados1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsiraOsNovosDados1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelInserirNovosDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAltura)
                    .addComponent(jLabelPeso)
                    .addComponent(jFormattedTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar1)
                    .addComponent(jButtonSalvar1)
                    .addComponent(jFormattedTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDadosCadastradosSucesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPreencherDados)
                .addGap(12, 12, 12))
        );

        jLabelDadosCadastradosSucesso.setVisible(false);
        jLabelPreencherDados.setVisible(false);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }

        this.jFormattedTextFieldCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        try {
            mascaraAltura = new MaskFormatter("#.##");
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }

        this.jFormattedTextFieldAltura.setFormatterFactory(new DefaultFormatterFactory(mascaraAltura));
        mascaraPeso();
        try {
            mascaraDataNascimento = new MaskFormatter("##-##-####");
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }

        this.jFormattedTextFieldDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNascimento));

        javax.swing.GroupLayout jPanelAtencaoLayout = new javax.swing.GroupLayout(jPanelAtencao);
        jPanelAtencao.setLayout(jPanelAtencaoLayout);
        jPanelAtencaoLayout.setHorizontalGroup(
            jPanelAtencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        jPanelAtencaoLayout.setVerticalGroup(
            jPanelAtencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtencaoLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCadastrarClienteLayout = new javax.swing.GroupLayout(jPanelCadastrarCliente);
        jPanelCadastrarCliente.setLayout(jPanelCadastrarClienteLayout);
        jPanelCadastrarClienteLayout.setHorizontalGroup(
            jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAtencao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                .addComponent(jPanelInserirNovosDados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCadastrarClienteLayout.setVerticalGroup(
            jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInserirNovosDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAtencao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cabecalho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("RESUMO DOS CLIENTES");

        jButtonVisaoGeral.setText("Visão Geral");
        jButtonVisaoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisaoGeralActionPerformed(evt);
            }
        });

        jButtonDeslogar.setText("Deslogar");
        jButtonDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeslogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(jButtonVisaoGeral)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeslogar)
                .addGap(18, 18, 18))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButtonVisaoGeral)
                    .addComponent(jButtonDeslogar))
                .addContainerGap())
        );

        jLabelBuscarCliente.setText("Buscar Cliente :");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addComponent(jLabelBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caixaBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoBuscar)
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscar)
                    .addComponent(caixaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCadastroJaExiste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCadastroJaExiste.setText("ATENÇÃO: Já existe um cadastro para esse CPF! Tente buscar na barra de pesquisa.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCadastroJaExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(jLabelCadastroJaExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jPanelCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        jLabelCadastroJaExiste.setVisible(false);

        setSize(new java.awt.Dimension(950, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        TelaCadastroModelo model = new TelaCadastroModelo();
        model.setNome(caixaBuscarCliente.getText());
        TelaCliente frm = new TelaCliente();
        try {
            frm.readTableClientePorNome(model.getNome());
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void jButtonDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeslogarActionPerformed
        new TelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDeslogarActionPerformed

    private void jButtonVisaoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisaoGeralActionPerformed
        new TelaVisualizacao().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVisaoGeralActionPerformed

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        Cliente c = new Cliente();
        ClienteDAO clienteDao = new ClienteDAO();
        boolean preenchidos = checarVazio();
        checarVazio();
        // Lê os campos e pega os dados que serão salvos
        c.setCpf(jFormattedTextFieldCpf.getText());
        c.setNome(jTextFieldNome.getText());
        try {
            c.setDataNascimento(sdf.parse(jFormattedTextFieldDataNascimento.getText()));
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }
        c.setAltura(Double.parseDouble(jFormattedTextFieldAltura.getText()));
        c.setPeso(Double.parseDouble(jFormattedTextFieldPeso.getText()));
        // Verifica se o cpf do cliente já está cadastrado no sistema
        boolean existe = false;
        try {
            existe = clienteDao.clienteExiste(jFormattedTextFieldCpf.getText());
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
        if (existe && preenchidos) {
            jLabelCadastroJaExiste.setVisible(true);
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    jLabelCadastroJaExiste.setVisible(false);
                    timer.cancel();
                }
            };

            timer.schedule(task, 3000L);
        } else if (preenchidos) {
            clienteDao.cadastrar(c);
            readTable();
            jFormattedTextFieldCpf.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldDataNascimento.setText("");
            jFormattedTextFieldAltura.setText("");
            jFormattedTextFieldPeso.setText("");

            jLabelDadosCadastradosSucesso.setVisible(true);
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    jLabelDadosCadastradosSucesso.setVisible(false);
                    timer.cancel();
                }
            };

            timer.schedule(task, 3000L);
        }
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        jFormattedTextFieldCpf.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldAltura.setText("");
        jFormattedTextFieldPeso.setText("");
        mascaraPeso();

    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JTextField caixaBuscarCliente;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonDeslogar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JButton jButtonVisaoGeral;
    private javax.swing.JFormattedTextField jFormattedTextFieldAltura;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelCadastroJaExiste;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDadosCadastradosSucesso;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelInsiraOsNovosDados1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPreencherDados;
    private javax.swing.JPanel jPanelAtencao;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCadastrarCliente;
    private javax.swing.JPanel jPanelInserirNovosDados1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableCadastrados;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    private boolean checarVazio() {
        boolean vazio = false;

        // Verifica se algum dos campos da JTable de cadastro está vazio ou com tamanho menor que o determinado
        if (jFormattedTextFieldCpf.getText().trim().length() < 14) {
            jFormattedTextFieldCpf.requestFocus();
            System.out.println("cpf" + jFormattedTextFieldCpf.getText().length());
            vazio = true;
        }
        if (jTextFieldNome.getText().trim().isEmpty()) {
            jTextFieldNome.requestFocus();
            vazio = true;
        }
        if (jFormattedTextFieldDataNascimento.getText().trim().length() < 10) {
            jFormattedTextFieldDataNascimento.requestFocus();
            System.out.println("data" + jFormattedTextFieldDataNascimento.getText().length());
            vazio = true;
        }
        if (jFormattedTextFieldAltura.getText().trim().length() < 4) {
            jFormattedTextFieldAltura.requestFocus();
            vazio = true;
        }
        if (jFormattedTextFieldPeso.getText().trim().length() < 5) {
            jFormattedTextFieldPeso.requestFocus();
            System.out.println("peso" + jFormattedTextFieldPeso.getText().trim().length());
            vazio = true;
        }

        // Caso algum campo esteja vazio não prosegue com a função de cadastro
        if (vazio) {
            jLabelPreencherDados.setVisible(true);
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    jLabelPreencherDados.setVisible(false);
                    timer.cancel();
                }
            };
            timer.schedule(task, 3000L);
            return false;
        }
        return true;
    }

    public void readTable() {
        // Popula a tabela na TelaCadastro com todos os clientes atualmente cadastrados no DB
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastrados.getModel();
        modelo.setNumRows(0);
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<>(modelo);
        jTableCadastrados.setRowSorter(sorter);
        ClienteDAO clienteDao = new ClienteDAO();

        try {
            for (Cliente cliente : clienteDao.getClientes()) {
                modelo.addRow(new Object[]{
                    cliente.getCpf(),
                    cliente.getNome(),
                    sdf.format(cliente.getDataNascimento()),
                    cliente.getAltura(),
                    cliente.getPeso()
                });
            }
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

    public void mascaraPeso() {
        // Mascara que determina a formatação do dado inserido
        jFormattedTextFieldPeso.setFormatterFactory(new JFormattedTextField.AbstractFormatterFactory() {

            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField tf) {
                DecimalFormat format = new DecimalFormat();
                format.setMinimumFractionDigits(2);
                format.setMaximumFractionDigits(2);
                format.setRoundingMode(RoundingMode.HALF_UP);

                DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols(getLocale());
                otherSymbols.setDecimalSeparator('.');

                format.setDecimalFormatSymbols(otherSymbols);
                NumberFormatter formatter = new NumberFormatter(format);
                formatter.setAllowsInvalid(false);
                formatter.setMinimum(0.00);
                formatter.setMaximum(999.99);
                return formatter;
            }

        });

    }

}
